services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data:/data
      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    env_file:
      ./configs/postgres.env
